### ISSUE TITLE
提示 line 86: transmission-remote: command not found

### ISSUE THREAD

**Issue by OwenLinZero** [qianbinbin/transmission-add-trackers#1]
执行过程，提示 line 86: transmission-remote: command not found
环境，群晖DSM6.2
直接使用ssh，bash执行脚本。

**Comment by qianbinbin** [comment]
`sudo find / -type f -name transmission-remote` 结果是什么？

**Comment by qianbinbin** [comment]
1. 确保 transmission-remote 存在。
2. 把脚本里的 transmission-remote 全部改为完整路径。

**Comment by OwenLinZero** [comment]
已解决。谢谢。
